Fix quadratic complexity while initializing KafkaMetrics
micrometer-metrics/micrometer pull request #2416
Opened 2021-01-25 15:11 UTC by kptfh

https://github.com/micrometer-metrics/micrometer/issues/2415

2021-02-17 03:28 UTC, shakuzen reviewed
I don't see how this changes the iterations required. Grouping by meter name would need to be done outside of the `metrics.forEach` loop to reduce iterations, unless I'm missing something.

2021-02-17 06:29 UTC, kptfh commented
Hi. Sure. It should be outside the loop. Inaccurately ported this change. Will fix.
Thank you for review.

2021-02-17 17:34 UTC, kptfh commented
fixed

2021-02-27 00:53 UTC, jonatan-ivanov commented
@kptfh It seems the compiler does not like it, could you please take a look?

2021-02-28 19:23 UTC, siim-romanov commented
Probably just needs to catch up with this change in master
https://github.com/micrometer-metrics/micrometer/pull/2418

2021-03-11 15:16 UTC, kptfh commented
@jonatan-ivanov @siim-romanov fixed

2021-05-13 16:31 UTC, kptfh commented
Hi guys! Do you have any comments regarding this pr?

2021-08-28 00:54 UTC, jonatan-ivanov requested changes

2021-08-28 00:54 UTC, jonatan-ivanov commented on micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaMetrics.java
> +                for (Meter other : metersForName) {
Is `metersWithLessTags` and `metersForName` really used here?
How about doing this:
```suggestion
                for (Meter other : registryMetersByNames.getOrDefault(meterName, emptyList())) {
```

And also removing `metersWithLessTags.add(other);` and `metersForName.removeAll(metersWithLessTags);`

2021-08-28 00:56 UTC, jonatan-ivanov commented
@kptfh Thanks for the fix, could you please rebase this to `1.6.x`?

2021-08-31 02:02 UTC, jonatan-ivanov approved these changes

2021-08-31 02:06 UTC, merged