Fix MultipleIndicator.combine()
micrometer-metrics/micrometer pull request #2439
Opened 2021-02-07 23:40 UTC by izeye

`MultipleIndicator.combine()` has a parameter named `objectives` somehow, so it uses the parameter instead of `this.objectives`.

This PR changes to use `this.objectives` simply by removing the parameter that seems to be added accidentally.

2021-02-08 20:35 UTC, jonatan-ivanov requested changes
Should not this go to 1.7?

2021-02-08 22:49 UTC, izeye commented
@jonatan-ivanov Thanks for the feedback!

I thought it needs to be fixed on the 1.6.x somehow. If the broken compatibility is unacceptable, how about deprecating the current one in favor of the new one?

2021-02-13 13:15 UTC, izeye commented
I changed to preserve the previous method with deprecation in 7b7c8d0.

2021-02-24 04:28 UTC, merged

2021-02-24 04:28 UTC, jonatan-ivanov commented
Thanks! :)

2021-02-24 04:48 UTC, izeye commented
@jonatan-ivanov Thanks for the review!

Micrometer 1.6.4 has been released already, so the Javadoc `@since` tag has been outdated now. I created #2473 to resolve it.