Kafka: Always get the current Metric instance from the metricsSupplier
micrometer-metrics/micrometer pull request #2770
Opened 2021-09-07 21:07 UTC by lbilger

Fixes #2726

See #2726 for details.

2021-09-08 23:02 UTC, jonatan-ivanov requested changes
Can we rebase this to 1.6.x so that other LTS versions could be fixed too?

2021-09-08 23:02 UTC, jonatan-ivanov commented on micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaMetrics.java
> +    private Meter bindMeter(MeterRegistry registry, Supplier<Map<MetricName, ? extends Metric>> metrics, MetricName metricName, String name, Iterable<Tag> tags) {
I think improving the variable names a little here and in the other methods would improve readability:
- `metrics` to `metricsSupplier`
- `name` to `meterName`

2021-09-08 23:03 UTC, jonatan-ivanov commented
@lbilger Thanks for the PR, I left a few comments: I think something behaves weirdly (though I tested it after I rebased your changes to `1.6.x`).

2021-09-09 08:10 UTC, lbilger commented
Hi Jonatan, thanks for having a look! I have rebased to 1.6.x, renamed the variables as requested and added a unit test. 

Can you share your test that showed the weird behavior? `metrics.get().get(metricName)` can return `null` if the metric is no longer present in the Consumer/Producer but `checkAndBindMetrics` has not yet been called since the metric was removed. If that is the case here, I would say it is correct and expected behavior to return NaN. If it is something else, I would have to investigate how it happens.

2021-09-09 19:51 UTC, jonatan-ivanov approved these changes

2021-09-09 19:57 UTC, jonatan-ivanov commented
The weird behavior was caused by me, in my sample (I used the kafka consumer + producer against a kafka instance), I closed the producer after sending the data so the kafka client removed a bunch of `KafkaMetric` instances so your fix did what it was expected to do, I somehow missed that my producer is closed.

2021-09-09 19:58 UTC, merged