Add ARM64 epoll for linux
micrometer-metrics/micrometer pull request #3605
Opened 2023-01-27 16:10 UTC by taer

I believe this is all that is needed to support UDS on ARM linux

2023-01-27 16:34 UTC, taer commented
The shaded jar now has this in it
```
micrometer/implementations/micrometer-registry-statsd/build/libs/META-INF/native on  addArm64Lib [$] using ☁️ dev-PowerUser 
➜ ls -l
total 336
-rw-rw-r-- 1 user user  74876 Jan 12 17:04 libio_micrometer_shaded_netty_resolver_dns_native_macos_aarch_64.jnilib
-rw-rw-r-- 1 user user  58104 Jan 12 16:55 libio_micrometer_shaded_netty_resolver_dns_native_macos_x86_64.jnilib
-rw-rw-r-- 1 user user 103728 Jan 12 14:36 libio_micrometer_shaded_netty_transport_native_epoll_aarch_64.so
-rw-rw-r-- 1 user user  94722 Jan 12 14:40 libio_micrometer_shaded_netty_transport_native_epoll_x86_64.so

```

2023-01-27 16:43 UTC, taer commented
I based on 1.9 since that was what I was using, but can rebase this on anything needed

2023-01-27 21:09 UTC, jonatan-ivanov commented
The branch is a good question (is this a feature or a bugfix? 😄).
I think if we decide to go with `1.9`, we might also want to back-port this (I can take care about it): https://github.com/micrometer-metrics/micrometer/pull/3139

@shakuzen What do you think? Should we go with `1.9` and also back-port the dns libs?

@taer Could you please double check the jar that you built and tested?
If you build it against `1.9.x`, you should have `epoll-x86` and `dns-macos-x86` (+`epoll_aarch_64` that you added) but in your list you also have `dns-macos-aarch_64` which tells me that your build was either against `1.10.x` or `main` since `1.9.x` should not have that.

2023-01-27 21:16 UTC, jonatan-ivanov requested changes

2023-01-27 21:16 UTC, jonatan-ivanov commented on implementations/micrometer-registry-statsd/build.gradle
> +    implementation(group: 'io.netty', name: 'netty-transport-native-epoll', classifier: 'linux-aarch_64')
In order to make this explicit, could you please also add the x86 variant?
(we did the same with dns-macos)
```suggestion
    implementation(group: 'io.netty', name: 'netty-transport-native-epoll', classifier: 'linux-aarch_64')
    implementation(group: 'io.netty', name: 'netty-transport-native-epoll', classifier: 'linux-x86_64')
```

2023-01-27 21:57 UTC, taer commented
> @taer Could you please double check the jar that you built and tested? If you build it against `1.9.x`, you should have `epoll-x86` and `dns-macos-x86` (+`epoll_aarch_64` that you added) but in your list you also have `dns-macos-aarch_64` which tells me that your build was either against `1.10.x` or `main` since `1.9.x` should not have that.

I had originally did it against master. And didn't clean.. This is the current one after a clean
```
-rw-rw-r-- 1 robert robert  58104 Dec 12 15:14 libio_micrometer_shaded_netty_resolver_dns_native_macos_x86_64.jnilib
-rw-rw-r-- 1 robert robert 103728 Dec 12 13:19 libio_micrometer_shaded_netty_transport_native_epoll_aarch_64.so
-rw-rw-r-- 1 robert robert  94722 Dec 12 13:21 libio_micrometer_shaded_netty_transport_native_epoll_x86_64.so

```

2023-01-27 21:59 UTC, taer commented
> The branch is a good question (is this a feature or a bugfix? smile).

Just something I just ran into. :)   I haven't tested it yet.. I know very little about native in java.

I'll try a quick test locally. See if it loads. The part that wasn't great was this didn't fail on ARM.. it just didn't work. Should there be some sort of error message or something in this case? Maybe there was a netty yelling on debug that I missed

2023-01-27 22:06 UTC, jonatan-ivanov approved these changes

2023-01-27 22:14 UTC, jonatan-ivanov commented
>I'll try a quick test locally. See if it loads. The part that wasn't great was this didn't fail on ARM.. it just didn't work. Should there be some sort of error message or something in this case? Maybe there was a netty yelling on debug that I missed

I'm not a big Netty wizard but as far as I know, if the native lib is not available, Netty should fallback to its Java implementation. This might not be the case of UDS (should be TCP/UDP under the hood though), it might worth creating an issue in the Netty repo if this is not an issue, a log message indeed would be nice.

2023-01-27 23:46 UTC, taer commented
Either way, I build this branch and deployed it, and it found the lib and reports to datadog! Looks happy and good to me

2023-01-31 01:19 UTC, merged

2023-01-31 01:19 UTC, jonatan-ivanov commented
@taer Thank you for the contribution!