fixes(logging) add warning message when 'OtlpMeterRegistry' fails to …
micrometer-metrics/micrometer pull request #4271
Opened 2023-10-24 09:19 UTC by antechrestos

…export metrics

2023-10-24 09:19 UTC, pivotal-cla commented
@antechrestos Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=micrometer-metrics/micrometer&pullRequestId=4271)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=micrometer-metrics/micrometer&pullRequestId=4271) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2023-10-24 09:20 UTC, pivotal-cla commented
@antechrestos Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=micrometer-metrics/micrometer&pullRequestId=4271)!

2023-10-24 19:16 UTC, jonatan-ivanov requested changes

2023-10-24 19:16 UTC, jonatan-ivanov commented on implementations/micrometer-registry-otlp/src/main/java/io/micrometer/registry/otlp/OtlpMeterRegistry.java
> +                    logger.warn("Failed to export metrics. Server responded with HTTP status code {} and body {}",
```suggestion
                    logger.warn("Failed to publish metrics. Server responded with HTTP status code {} and body {}",
```

2023-10-24 19:18 UTC, jonatan-ivanov commented
Thank you for the PR!
I think this makes sense. I believe we should do this on the `1.10.x` branch so not only 1.12 but 1.11 and 1.10 will get this fix. Could you please rebase your changes on the `1.10.x` branch?

2023-10-24 19:20 UTC, antechrestos commented
@jonatan-ivanov of course. I will do it by tomorrow with your suggestion.
Thank you

2023-10-24 20:50 UTC, antechrestos commented
@jonatan-ivanov I made the following change

* applied suggestion
* change target branch (with rebase)


Cheers

2023-10-25 19:22 UTC, jonatan-ivanov approved these changes

2023-10-25 19:23 UTC, merged

2023-10-25 19:23 UTC, jonatan-ivanov commented
Thank you!

2023-10-25 21:29 UTC, jonatan-ivanov commented
Nope, once it is merged to a maintenance branch the person who merged it should forward merge it to the other supported branches too. I've already taken care of forward merging and resolving the merge conflicts (as you noticed, the code changed a bit). This change is now available on `1.10.x`, `1.11.x`, and `main`, see https://github.com/micrometer-metrics/micrometer/commit/538ba6ac85599dc36284a12c5849333cf78c6023 and https://github.com/micrometer-metrics/micrometer/commit/32fe2c54006f330036f8cc181610a53852864ffb

You can try out any latest snapshot versions, e.g.: `1.12.0-SNAPSHOT`, it should contain your changes, thank you again for fixing this!