Add support for `AutoShutdownDelegatedExecutorService`
micrometer-metrics/micrometer pull request #4315
Opened 2023-11-04 19:21 UTC by nscuro

This executor is returned by `Executors#newSingleThreadExecutor` under Java 21.

2023-11-04 19:21 UTC, pivotal-cla commented
@nscuro Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=micrometer-metrics/micrometer&pullRequestId=4315)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=micrometer-metrics/micrometer&pullRequestId=4315) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2023-11-04 19:22 UTC, pivotal-cla commented
@nscuro Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=micrometer-metrics/micrometer&pullRequestId=4315)!

2024-12-20 08:08 UTC, shakuzen requested changes
Thank you for the pull request. Would you please add tests that verify the metrics work with Executors of the new type added?

2025-01-08 00:26 UTC, jonatan-ivanov commented
@nscuro Could you please add some tests?

2025-01-08 06:51 UTC, shakuzen commented
I went ahead and added a test for it (to our micrometer-java21 module's tests since it requires JDK 21+):

```java
// See gh-4315
@Test
void threadPoolMetricsWith_AutoShutdownDelegatedExecutorService() throws InterruptedException {
    CountDownLatch latch = new CountDownLatch(1);
    ExecutorService unmonitored = Executors.newSingleThreadExecutor();
    assertThat(unmonitored.getClass().getName()).isEqualTo("java.util.concurrent.Executors$AutoShutdownDelegatedExecutorService");
    ExecutorService monitored = ExecutorServiceMetrics.monitor(registry, unmonitored, "test");
    monitored.execute(latch::countDown);
    assertThat(latch.await(100, TimeUnit.MILLISECONDS)).isTrue();
    assertThat(registry.get("executor.completed")
        .tag("name", "test")
        .functionCounter()
        .count()).isEqualTo(1L);
}
```

The test still fails; just the warning logged is different. So I don't think this PR effectively changes anything, unless I'm missing something.

```
Jan 08, 2025 3:40:38 PM io.micrometer.core.instrument.binder.jvm.ExecutorServiceMetrics unwrapThreadPoolExecutor
INFO: Cannot unwrap ThreadPoolExecutor for monitoring from java.util.concurrent.Executors$DelegatedExecutorService due to java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.util.concurrent.ExecutorService java.util.concurrent.Executors$DelegatedExecutorService.e accessible: module java.base does not "opens java.util.concurrent" to unnamed module @60985c7c

io.micrometer.core.instrument.search.MeterNotFoundException: Unable to find a meter that matches all the requirements at once. Here's what was found:
   FAIL: No meter with name 'executor.completed' was found.
   FAIL: No meters with type function counter were found.
   FAIL: No meters have the required tag 'name'.
```

Given the above, I'll close this PR. If we have another way of enabling the additional metrics, let's explore that, but I'm not sure it's worth changing the logged warning from one thing to another. Let me know if I've missed anything.

2025-01-08 06:51 UTC, closed without merging

2025-01-18 10:52 UTC, izeye commented
`--add-opens java.base/java.util.concurrent=ALL-UNNAMED` seems to be required for this change to work.

I created https://github.com/micrometer-metrics/micrometer/pull/5811 on top of this PR and the test that @shakuzen wrote above.