Minor change: Align the types of elements on which @Timed and @Counted can be applied
micrometer-metrics/micrometer pull request #4502
Opened 2023-12-20 08:57 UTC by baeyenwo

Add `ElementType.ANNOTATION_TYPE`, `ElementType.TYPE` as targetTypes to `@Counted`

`@Timed` and `@Counted` are used in very similar ways. 
However the type of elements where the annotation is allowed is not aligned.

This pr proposes to fix the inconsistency.

2023-12-20 08:57 UTC, pivotal-cla commented
@baeyenwo Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=micrometer-metrics/micrometer&pullRequestId=4502)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=micrometer-metrics/micrometer&pullRequestId=4502) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2023-12-20 09:01 UTC, pivotal-cla commented
@baeyenwo Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=micrometer-metrics/micrometer&pullRequestId=4502)!

2023-12-22 14:42 UTC, marcingrzejszczak approved these changes

2024-01-16 04:37 UTC, shakuzen requested changes
We should add tests that prove this works on the new targets.

2024-02-02 09:22 UTC, shakuzen commented
I tried adding a test to `CountedAspectTest` for this and it fails. We'll need to update the `CountedAspect` implementation to handle the new targets before we would want to merge this.

```java
@Test
void countClass() {
    CountedClassService service = getAdvisedService(new CountedClassService());

    service.hello();

    assertThat(meterRegistry.get("class.counted")
        .tag("class", "io.micrometer.core.aop.CountedAspectTest$CountedClassService")
        .tag("method", "hello")
        .counter()
        .count()).isEqualTo(1);
}

@Counted("class.counted")
static class CountedClassService {
    String hello() {
        return "hello";
    }

    void fail() {
        throw new RuntimeException("Oops");
    }
}
```

2024-02-13 01:46 UTC, closed without merging

2024-02-13 05:16 UTC, shakuzen commented
I've opened #4746 for tracking this work.