Fixes #4976 - added optional custom scheduler to Consumer KafkaClientMetrics
micrometer-metrics/micrometer pull request #4977
Opened 2024-04-20 17:26 UTC by vasiliy-sarzhynskyi

2024-04-20 17:31 UTC, vasiliy-sarzhynskyi commented
It's a proposed contribution for [enhancement #4976](https://github.com/micrometer-metrics/micrometer/issues/4976) to extend `KafkaMetrics` with custom scheduler

2024-10-08 07:00 UTC, shakuzen reviewed
Thank you for the pull request. This looks reasonable to me. Before merging, I'm trying to get an idea of the impact to other projects so this can be most easily used by end users. What would change in Spring Kafka and Spring Boot? I guess `MicrometerConsumerListener` in Spring Kafka would need to optionally take a `ScheduledExecutorService` and `KafkaMetricsAutoConfiguration` in Spring Boot would need a way to get a `ScheduledExecutorService` from user configuration (how would it do this?) to pass to the `MicrometerConsumerListener` it makes.

@artembilan do you have any concerns about this from a Spring Kafka perspective?

2024-10-08 14:57 UTC, artembilan requested changes

2024-10-09 01:08 UTC, shakuzen commented on micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaClientMetrics.java
> +    public KafkaClientMetrics(Consumer<?, ?> kafkaConsumer, Iterable<Tag> tags, ScheduledExecutorService scheduler) {
Thanks for the review @artembilan.
@vasiliy-sarzhynskyi any reason to not add similar constructors for producers and admin clients?

2024-10-09 16:48 UTC, vasiliy-sarzhynskyi commented on micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaClientMetrics.java
> +    public KafkaClientMetrics(Consumer<?, ?> kafkaConsumer, Iterable<Tag> tags, ScheduledExecutorService scheduler) {
@shakuzen I need to check how producers and admin clients are used by Spring-Kafka, and how many threads we might have with multiple produced topics (whether the number of threads increased or not).  We could add there as well, but do we have use cases when producers and admin clients might need that? In my understanding, it's especially relevant for consumers as we might specify `concurrency` config value, and a single app instance will have hundreds of threads.

2024-10-09 17:02 UTC, artembilan commented on micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaClientMetrics.java
> +    public KafkaClientMetrics(Consumer<?, ?> kafkaConsumer, Iterable<Tag> tags, ScheduledExecutorService scheduler) {
I’m not sure how is this relevant to the use of those clients in the app, the scheduler we provide here is used for publishing metrics from those clients. See `bindTo()` impl.

2024-10-10 15:43 UTC, shakuzen commented on micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaClientMetrics.java
> +    public KafkaClientMetrics(Consumer<?, ?> kafkaConsumer, Iterable<Tag> tags, ScheduledExecutorService scheduler) {
This scheduler isn't for publishing; MeterRegistry implementations can be configured with a scheduler to publish metrics. This scheduler is for syncing the metrics from the Kafka client to Micrometer's registry periodically. The background is in https://github.com/micrometer-metrics/micrometer/issues/4976, but with many clients and the existing code, each client will have a thread for syncing between the Kafka client's metrics and Micrometer. With the changes here, a thread pool could be shared among the clients for this syncing.

2024-10-10 16:06 UTC, vasiliy-sarzhynskyi commented on micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaClientMetrics.java
> +    public KafkaClientMetrics(Consumer<?, ?> kafkaConsumer, Iterable<Tag> tags, ScheduledExecutorService scheduler) {
Thank you. In that case, I will update the current PR for `Producer` and `Admin` as well

2024-10-11 17:03 UTC, vasiliy-sarzhynskyi commented on micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaClientMetrics.java
> +    public KafkaClientMetrics(Consumer<?, ?> kafkaConsumer, Iterable<Tag> tags, ScheduledExecutorService scheduler) {
@shakuzen I pushed my changes for `Producer` and `AdminClient` constructors as well. After I rebased on branch `main`, recently added test class `VirtualThreadMetricsTests` is failing, looks like it's flaky.
I could try to increase the upper bound threshold inside `VirtualThreadMetricsTests pinnedEventsShouldBeRecorded(..)`, but would be better to contact owner of these changes to clarify the intention of asserted values

2024-10-12 05:23 UTC, shakuzen commented on micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaClientMetrics.java
> +    public KafkaClientMetrics(Consumer<?, ?> kafkaConsumer, Iterable<Tag> tags, ScheduledExecutorService scheduler) {
Pinging @jonatan-ivanov about the flakiness of `VirtualThreadMetricsTests`. I'll re-run the CI manually in the meantime.

2024-10-12 05:31 UTC, shakuzen approved these changes
Thanks for the pull request and quick response to review. This looks good to me. I'll polish a couple things when merging.

2024-10-15 04:39 UTC, shakuzen commented
I've added the same changes for `KafkaStreamsMetrics` and updated the JavaDocs to specifically mention the purpose and responsibilities for the custom scheduler.

2024-10-15 04:51 UTC, merged