Validate cloudwatch2 registry using localstack
micrometer-metrics/micrometer pull request #4979
Opened 2024-04-21 16:47 UTC by sullis

2024-04-21 17:50 UTC, sullis commented
Ready for review

2024-04-22 07:55 UTC, shakuzen commented
Thank you for the pull request. This is something we've been wanting to do for a long time, and this looks like it should be a good approach.

2024-04-23 05:13 UTC, jonatan-ivanov requested changes
Thank you for the PR, we definitely would like to have more integration tests!

Though I think in this form this might not be a real integration test yet or I might misunderstand what is happening here.

As the PR looks right now, I don’t get why localstack is needed. It seems verification happens against the mock (spy) so wether there was an http API call to CloudWatch (what would make this an integration test) is irrelevant from the test's point of view.

I think in order to make this an integration test and justify the usage of localstack, the test should call the AWS SDK to check if the published data is in localstack (CloudWatch) or not otherwise this could be a unit test with a different mocked/fake client without localstack (we might already have that kind of tests).

Could you please check if you can call the same cloudwatch client to get the data that was published by the registry and run verification against that data?

2024-04-23 05:13 UTC, jonatan-ivanov commented on gradle/libs.versions.toml
> +awsSdk2 = "2.25.26"
`cloudwatch2` might be a better name since this is not the whole AWSD SDK.

2024-04-23 05:13 UTC, jonatan-ivanov commented on gradle/libs.versions.toml
> +awsSdk2NettyClient = { module = "software.amazon.awssdk:netty-nio-client", version.ref = "awsSdk2" }
Can't we use the default client shipped with the cloudwatch dependency?

2024-04-23 05:13 UTC, jonatan-ivanov commented on implementations/micrometer-registry-cloudwatch2/build.gradle
> +    testImplementation(libs.logbackLatest)
Why do we need this?

2024-06-27 01:50 UTC, closed without merging