Added support of @MeterTag annotation on method level
micrometer-metrics/micrometer pull request #5587
Opened 2024-10-11 12:24 UTC by MarinaMoiseenko

Fixes #3058.

@jonatan-ivanov, @shakuzen please take a look, These are changes discussed in #3058.

2024-12-20 08:37 UTC, shakuzen commented
Thanks for the pull request. Could you rebase on the latest `main` and resolve the conflicts?

2025-01-08 00:24 UTC, jonatan-ivanov requested changes
@MarinaMoiseenko Could you rebase on the latest main and resolve the conflicts?

2025-01-13 07:06 UTC, MarinaMoiseenko commented
Yes, will do.

2025-01-26 16:19 UTC, MarinaMoiseenko commented
please consider https://github.com/micrometer-metrics/micrometer/pull/5827 instead

2025-01-27 01:36 UTC, closed without merging