Apply gh-5553 to io.micrometer.core.instrument.binder.jdk
micrometer-metrics/micrometer pull request #5704
Opened 2024-11-23 06:59 UTC by izeye

This PR applies the changes made in gh-5553 to the classes in the `io.micrometer.core.instrument.binder.jdk` package.

2024-11-25 04:50 UTC, shakuzen approved these changes

2024-11-25 23:09 UTC, jonatan-ivanov requested changes

2024-11-26 01:11 UTC, izeye commented on micrometer-core/src/test/java11/io/micrometer/core/instrument/binder/jdk/MicrometerHttpClientTests.java
> +            // TODO fix status/uri in exceptional cases where response may be null
@jonatan-ivanov I just copied it from 81b53d3163e951e9c7abd4a4b8a9109927d6e9d7, and actually I made some polishing on it in https://github.com/micrometer-metrics/micrometer/pull/5705, but I didn't apply it here as I was sure about it.

2024-11-26 01:13 UTC, izeye commented on micrometer-core/src/main/java11/io/micrometer/core/instrument/binder/jdk/MicrometerHttpClient.java
> +            stopObservationOrTimer(instrumentation, request, response);
@jonatan-ivanov Sorry, I'll fix it and add a test shortly.

Actually I made the same mistake in https://github.com/micrometer-metrics/micrometer/pull/5708. I'll create another PR to fix it.

2024-11-26 01:24 UTC, izeye commented on micrometer-core/src/main/java11/io/micrometer/core/instrument/binder/jdk/MicrometerHttpClient.java
> +            stopObservationOrTimer(instrumentation, request, response);
> Actually I made the same mistake in #5708. I'll create another PR to fix it.

@jonatan-ivanov I created https://github.com/micrometer-metrics/micrometer/pull/5709 to fix it.

2024-11-26 01:25 UTC, izeye commented
@jonatan-ivanov Thanks for the feedback! I applied your suggestions.

2024-12-04 19:14 UTC, jonatan-ivanov approved these changes

2024-12-04 19:14 UTC, merged

2024-12-04 19:16 UTC, jonatan-ivanov commented
Thank you!