Handle RuntimeException when getting/setting JMS headers
micrometer-metrics/micrometer pull request #5746
Opened 2024-12-17 14:20 UTC by cfredri4

Currently JMSException is handled when getting/setting JMS headers. Some JMS providers will throw RuntimeException instead of JMSException when failing to get/set JMS headers. This change adds so that RuntimeException is also handled.

For example, [Qpid JMS throws IllegalArgumentException](https://github.com/apache/qpid-jms/blob/main/qpid-jms-client/src/main/java/org/apache/qpid/jms/message/JmsMessagePropertySupport.java#L101) which leads to similar issue as #4202.

2024-12-17 23:03 UTC, jonatan-ivanov reviewed
Thank you for the PR!

I'm thinking about the consequences of doing this: since this can happen if a propagation format that contains `-` is used, this can hide the underlying problem and propagation still won't work.

I'm wondering if we should log a warning (maybe a warning first then debug using `WarnThenDebugLogger`). What do you think?

/cc @bclozel @shakuzen

2024-12-18 19:10 UTC, jonatan-ivanov requested changes

2024-12-18 19:10 UTC, jonatan-ivanov commented on micrometer-jakarta9/src/main/java/io/micrometer/jakarta9/instrument/jms/JmsProcessObservationContext.java
> +                logger.log("Failed get message property.", exc);
```suggestion
                logger.log("Failed to get message property.", exc);
```

2024-12-18 19:10 UTC, jonatan-ivanov commented on micrometer-jakarta9/src/main/java/io/micrometer/jakarta9/instrument/jms/JmsPublishObservationContext.java
> +                    logger.log("Failed set message property.", exc);
```suggestion
                    logger.log("Failed to set message property.", exc);
```

2024-12-18 19:12 UTC, jonatan-ivanov commented on micrometer-jakarta9/src/main/java/io/micrometer/jakarta9/instrument/jms/JmsProcessObservationContext.java
> +            catch (JMSException | RuntimeException exc) {
Should we do `catch (Exception exc)`?

2024-12-18 19:14 UTC, jonatan-ivanov commented
I think we should do this against `1.13.x` but I can back-port this and modify the PR before merging.

2024-12-19 07:49 UTC, cfredri4 commented
Pushed fixes. 👍

2025-01-07 01:04 UTC, shakuzen approved these changes
Looks good to me. It might help our future selves know why we're catching Exception if there's a comment with the reasoning.

2025-01-10 00:18 UTC, closed without merging